# -*- coding: utf-8 -*-
"""Aula 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S4-AnuE_fmLtdHMqR0RUSU-6OHXx8Rjt
"""

import pandas as pd
df  = pd.read_csv("https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv")
df.isnull().sum()

df['work_year'].unique()

#df.isnull().any(axis = 1)
df[df.isnull().any(axis = 1)]

import numpy as np

#criacao de uma base de testes
df_salarios = pd.DataFrame({
    'nome': ['Ana', 'Bruno', 'Carlos', 'Daniele', 'Val'],
    'salario': [4000, np.nan, 5000, np.nan, 100000]
})

#media
df_salarios['salario_media'] = df_salarios['salario'].fillna(df_salarios['salario'].mean().round(2))

#mediana
df_salarios['salario_mediana'] = df_salarios['salario'].fillna(df_salarios['salario'].median())

df_salarios

df_temperaturas  = pd.DataFrame({
    'Dia': ['Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta'],
    'Temperatura': [30, np.nan, np.nan, 28, 27]
})

#complete com o valor anterior
df_temperaturas['preenchido_ffill'] = df_temperaturas['Temperatura'].ffill()

#complete com o proximo valor
df_temperaturas['preenchido_bfill'] = df_temperaturas['Temperatura'].bfill()
df_temperaturas

df_cidades = pd.DataFrame({
    'nome': ['Ana', 'Bruno', 'Carlos', 'Daniele', 'Val'],
    'cidade': ['São Paulo', np.nan, 'Curitiba', np.nan, 'Belem']
})

df_cidades['cidade_preenchida'] = df_cidades['cidade'].fillna('Não informado')

df_cidades

df_dados_tratados = df.dropna()
# df_dados_tratados.isnull().sum()
# df_dados_tratados.head()
# df_dados_tratados.info()

df_dados_tratados = df_dados_tratados.assign(work_year = df_dados_tratados['work_year'].astype('int64'))
df_dados_tratados.head()
df_dados_tratados.info()