# -*- coding: utf-8 -*-
"""Aula 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fe5do5hdWX9naxJ3yFVAwRz2hlwhIA-c
"""

import pandas as pd

df  = pd.read_csv("https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv")

df.head(10)

df.info()

df.describe()

df.shape

linhas, colunas = df.shape[0], df.shape[1]
print("linhas: ", linhas)
print("colunas: ", colunas)

df.columns

colunas_pt_br = {
    'ano': 'ano',
    'nivel_experiencia': 'senioridade',
    'tipo_emprego': 'contrato',
    'titulo_cargo': 'cargo',
    'salario': 'salario',
    'moeda_salario': 'moeda',
    'salario_em_usd': 'usd',
    'residencia_empregado': 'residencia',
    'taxa_remoto': 'remoto',
    'empresa': 'local_empresa',
    'tamanho_empresa': 'tamanho_empresa'
}

df.rename(columns = colunas_pt_br, inplace=True)

df.columns

df["senioridade"].value_counts()

df["contrato"].value_counts()

df["remoto"].value_counts()

df["local_empresa"].value_counts()

df["tamanho_empresa"].value_counts()







traducao_remoto = {
    0: 'Presencial',
    50: 'Híbrido',
    100: 'Remoto'
}

df['remoto'] = df['remoto'].replace(traducao_remoto)

display(df['remoto'].value_counts())

df.head()

