# -*- coding: utf-8 -*-
"""Aula_4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DXIy6pFi_Fpqz6nTI6F5iq59eY-UrC0_
"""

import pandas as pd

df  = pd.read_csv("https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv")
df_dados_tratados = df.dropna()
df_dados_tratados = df_dados_tratados.assign(work_year = df_dados_tratados['work_year'].astype('int64'))
df_dados_tratados = df_dados_tratados.rename(columns={
    'ano_trabalho': 'ano_contratacao',
    'experience_level': 'nivel_experiencia',
    'employment_type': 'tipo_emprego',
    'job_title': 'cargo',
    'salary': 'salario',
    'salary_currency': 'moeda_salario',
    'salary_in_usd': 'salario_em_usd',
    'employee_residence': 'residencia_empregado',
    'remote_ratio': 'proporcao_remoto',
    'company_location': 'localizacao_empresa',
    'company_size': 'tamanho_empresa'
})
df_dados_tratados['nivel_experiencia'] = df_dados_tratados['nivel_experiencia'].replace({
    'EN': 'Iniciante',
    'MI': 'Intermediário',
    'SE': 'Sênior',
    'EX': 'Executivo'
})

df_data_scientist = df_dados_tratados[df_dados_tratados['cargo'] == 'Data Scientist']
df_data_scientist

pip install pycountry

import pycountry
import plotly.express as px

# Função para converter ISO-2 para ISO-3
def iso2_to_iso3(code):
    try:
        return pycountry.countries.get(alpha_2=code).alpha_3
    except:
        return None

df_dados_tratados['localizacao_empresa_iso3'] = df_dados_tratados['localizacao_empresa'].apply(iso2_to_iso3)

df_data_scientist = df_dados_tratados[df_dados_tratados['cargo'] == 'Data Scientist']
df_media_pais = df_data_scientist.groupby('localizacao_empresa_iso3')['salario_em_usd'].mean().reset_index()

fig = px.choropleth(
    df_media_pais,
    locations='localizacao_empresa_iso3',
    color='salario_em_usd',
    color_continuous_scale='rdylgn',
    title='Média de Salário por País',
    labels={'salario_em_usd': 'Salário Médio (USD)', 'localizacao_empresa_iso3': 'País'}
    )

fig.show()

df_mediana_pais = df_data_scientist.groupby('localizacao_empresa_iso3')['salario_em_usd'].median().reset_index()

fig = px.choropleth(
    df_mediana_pais,
    locations='localizacao_empresa_iso3',
    color='salario_em_usd',
    color_continuous_scale='rdylgn',
    title='Médiana de Salário por País',
    labels={'salario_em_usd': 'Mediana dos salários (USD)', 'localizacao_empresa_iso3': 'País'}
    )

fig.show()

df_dados_tratados.to_csv('dados_tratados.csv', index=False)